ingore syncer-chart for coredns
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

ingore syncer-chart for coredns

Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -32,8 +32,12 @@ e2e:
             	echo "the project $${ITEM}  needs a standby kind cluster" ; \
 				make init-kind -e KIND_CONFIG_PATH=$${CONFIG_PATH} || { echo "error, failed to setup kind for $${ITEM}"; exit 1 ;} ; \
             fi ; \
-			echo "sync project $${ITEM}"; \
-			make sync -e PROJECT=$${ITEM} || { echo "error, failed to sync $${ITEM}" ; exit 1 ; } ; \
+            if source $(ROOT_DIR)/charts/$${ITEM}/config && [ "$${NO_IMAGE}" == "true" ] ; then \
+              	echo "ignore sync project $${ITEM}"; \
+            else \
+				echo "sync project $${ITEM}"; \
+				make sync -e PROJECT=$${ITEM} || { echo "error, failed to sync $${ITEM}" ; exit 1 ; } ; \
+            fi ; \
 			echo "deploy project $${ITEM}"; \
 			make deploy -e INSTALL_PATH=$${INSTALL_PATH}  -e PROJECT=$${ITEM} || { echo "error, failed to deploy $${ITEM}" ; exit 1 ; } ; \
 	  	done ; \
@@ -53,8 +57,12 @@ e2e:
 						echo "the project $${ITEM}  needs a standby kind cluster" ; \
 						make init-kind -e KIND_CONFIG_PATH=$${CONFIG_PATH} || { echo "error, failed to setup kind for $${ITEM}"; exit 1 ;} ; \
 					fi ; \
-					echo "sync project $${ITEM}"; \
-					make sync -e PROJECT=$${ITEM} || { echo "error, failed to sync $${ITEM}" ; exit 1 ; } ; \
+					if source $(ROOT_DIR)/charts/$${ITEM}/config && [ "$${NO_IMAGE}" == "true" ] ; then \
+						echo "ignore sync project $${ITEM}"; \
+					else \
+						echo "sync project $${ITEM}"; \
+						make sync -e PROJECT=$${ITEM} || { echo "error, failed to sync $${ITEM}" ; exit 1 ; } ; \
+					fi ; \
 					echo "deploy project $${ITEM}"; \
 					make deploy -e INSTALL_PATH=$${INSTALL_PATH}  -e PROJECT=$${ITEM} || { echo "error, failed to deploy $${ITEM}" ; exit 1 ; } ; \
 				done ; \
