test
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -60,13 +60,13 @@ deploy: TRY_LOAD_LOCAL_IMAGE ?= true
 deploy: checkBin
 	@ echo "helm install for $(PROJECT) with $(INSTALL_PATH)"
 	@ [ -f "$(INSTALL_PATH)" ] || { echo "error, failed to find INSTALL_PATH $(INSTALL_PATH)" ;  exit 1 ; }
-	@ CHART_DIR=$(ROOT_DIR)/charts/$(PROJECT)/$(PROJECT) ; \
+	CHART_DIR=$(ROOT_DIR)/charts/$(PROJECT)/$(PROJECT) ; \
 		[ -d "$${CHART_DIR}" ] || { echo "error, failed to find chart $${CHART_DIR}" ; exit 1 ; } ; \
 		if [ "$(TRY_LOAD_LOCAL_IMAGE)" == "true" ] ; then \
 			echo "try to load local image for $(PROJECT)" ; \
 			IMAGE_LIST=` helm template test $${CHART_DIR}  |& grep " image: " | awk -F '"' '{print $$2}' ` ; \
 			if [ -z "$${IMAGE_LIST}" ] ; then \
-			  	echo "error, failed to find image from chart template for $(PROJECT)" ; \
+			  	echo "warning, failed to find image from chart template for $(PROJECT)" ; \
 			else \
 				echo "found image from $(PROJECT) chart template: $${IMAGE_LIST} " ; \
   				for IMAGE in $${IMAGE_LIST} ; do \
@@ -77,8 +77,8 @@ deploy: checkBin
 		fi  ;\
 		chmod +x $(INSTALL_PATH) ; \
 		$(INSTALL_PATH) "$${CHART_DIR}"  "$(KIND_KUBECONFIG)" ; \
-		(($?==0)) || { echo "error, failed to deploy $(PROJECT) "  ; exit 1 ; }
-	echo "succeeded to deploy $(PROJECT)"
+		(($?==0)) || { echo "error, failed to deploy $(PROJECT) "  ; exit 1 ; } ; \
+		echo "succeeded to deploy $(PROJECT)"
 
 
 .PHONY: checkBin
